### ISSUE TITLE
^ for event bubbling was removed in alpha.38

### ISSUE THREAD

**Issue by mrajcok** [driftyco/learn-angular2#12]
http://learnangular2.com/templates/ states "To use event delegation, where an event on a child will bubble up to the parent, use the ^ before the event name"

alpha.38 removed this: "remove the (^ syntax and make all DOM events bubbling)"
https://github.com/angular/angular/blob/master/CHANGELOG.md#core

**Comment by mhartington** [comment]
Should have been fixed via https://github.com/driftyco/learn-angular2/commit/7b74fcde6190fab14e129e27fe70a2c42326b312
