### ISSUE TITLE
Confusing syntax

### ISSUE THREAD

**Issue by Donal-Flanagan** [driftyco/learn-angular2#38]
http://learnangular2.com/outputs/
The above @Output example is very nice but naming both the event emitter and the method userUpdated is unnecessary and very confusing. 

It leads to the following line of code:
 <user-profile (userUpdated)="userUpdated($event)"></user-profile>

I took this to mean that the $event was being return by "userUpdated()" in <user-profile> and assigned as the input for (userUpdated). The opposite is actually true.
This could be easily fixed with better naming.

**Comment by mhartington** [comment]
Should be updated now
